[phases.setup]
nixPkgs = ["python39"]

[phases.install]
cmds = ["pip install -r requirements-production.txt"]

[phases.build]
cmds = ["python manage.py collectstatic --noinput"]

[start]
cmd = "python manage.py migrate && gunicorn garmently_backend.wsgi:application --bind 0.0.0.0:${PORT:-8000}"
